import type { Language } from '@jupiter/contracts';

const en = {
  appName: 'Jupiter',
  appShell: 'Jupiter command center',
  skipToContent: 'Skip to main content',
  primaryNavigation: 'Primary navigation',
  collapseNavigation: 'Collapse navigation',
  expandNavigation: 'Expand navigation',
  home: 'Home',
  chat: 'Chat',
  missions: 'Missions',
  skills: 'Skills',
  memory: 'Memory',
  files: 'Files',
  automations: 'Automations',
  models: 'AI Models',
  devices: 'Devices',
  plugins: 'Plugins',
  settings: 'Settings',
  diagnostics: 'Diagnostics',
  operational: 'Operational',
  degraded: 'Degraded',
  offline: 'Offline',
  unavailable: 'Unavailable',
  notConfigured: 'Not configured',
  comingLater: 'Coming later',
  experimental: 'Experimental',
  loading: 'Checking Jupiter Core…',
  retry: 'Retry',
  close: 'Close',
  refresh: 'Refresh health',
  saveError: 'Jupiter could not save that preference.',
  preferenceSaved: 'Preference saved',
  toastRegion: 'Jupiter notifications',
  coreOnline: 'Jupiter Core online',
  coreLimited: 'Jupiter Core has limited availability',
  coreUnavailable: 'Jupiter Core unavailable',
  homeEyebrow: 'Command Center',
  homeTitle: 'Ready when real capabilities are configured.',
  homeDescription:
    'Jupiter Core is connected. Agent, model, and Mission capabilities remain unavailable until their implementation SETs.',
  currentMission: 'Current Mission',
  noActiveMission: 'No active Mission',
  noActiveMissionDescription:
    'Mission execution begins in a later SET. Jupiter is not running background work.',
  progressUnavailable: 'Progress unavailable',
  elapsedTime: 'Elapsed time',
  agent: 'Agent',
  skill: 'Skill',
  model: 'Model',
  none: 'None',
  pause: 'Pause',
  cancel: 'Cancel',
  details: 'Details',
  timeline: 'Activity timeline',
  timelineEmpty: 'No Core activity has been recorded in this UI session.',
  eventCoreStarted: 'Jupiter Core started',
  eventCoreStopped: 'Jupiter Core stopped',
  eventServiceHealth: 'Service health changed',
  eventPreferencesUpdated: 'Interface preferences updated',
  eventRecorded: 'Core event recorded',
  chatTitle: 'Chat',
  chatDescription: 'AI providers and chat are not configured in SET 2.',
  composerLabel: 'Message composer',
  composerPlaceholder: 'AI provider not configured',
  send: 'Send',
  missionsTitle: 'Missions',
  missionsDescription: 'Mission planning and execution arrive in a later SET.',
  skillsTitle: 'Skills',
  skillsDescription: 'No Skills are installed because the Skill system is not implemented yet.',
  memoryTitle: 'Memory',
  memoryDescription: 'Jupiter is not saving personal memory in SET 2.',
  filesTitle: 'Files and artifacts',
  filesDescription: 'No file roots are approved and no artifacts are managed yet.',
  automationsTitle: 'Automations',
  automationsDescription: 'No schedules or background automations are running.',
  modelsTitle: 'AI Models',
  modelsDescription: 'No cloud or local AI provider is configured.',
  devicesTitle: 'Devices',
  devicesDescription: 'Microphone, camera, and companion devices are not connected.',
  pluginsTitle: 'Plugins',
  pluginsDescription: 'No third-party plugin runtime is enabled.',
  settingsTitle: 'Settings',
  settingsDescription: 'These interface preferences are real and persist locally.',
  appearance: 'Appearance',
  accessibility: 'Accessibility',
  safetyInterfaces: 'Safety interfaces',
  language: 'Language',
  english: 'English',
  thai: 'ไทย',
  theme: 'Theme',
  darkTheme: 'Graphite',
  midnightTheme: 'Midnight',
  avatar: 'Jupiter avatar',
  avatarAnimated: 'Animated',
  avatarStatic: 'Static',
  avatarHidden: 'Hidden',
  reduceMotion: 'Reduce motion',
  compactMode: 'Compact mode',
  textScale: 'Text size',
  permissionInterface: 'Permission dialog',
  identityInterface: 'Identity dialog',
  viewAvailability: 'View availability details',
  permissionTitle: 'Permission confirmation',
  permissionDescription: 'Permission Engine unavailable',
  permissionBody:
    'This dialog shell is accessible, but it cannot approve actions until the Permission Engine is implemented.',
  identityTitle: 'Identity verification',
  identityDescription: 'Identity Engine unavailable',
  identityBody:
    'No identity proof is collected or simulated. Identity verification arrives in a later SET.',
  windowsNotifications: 'Windows notifications',
  windowsNotificationsBody:
    'Bridge interface available; native delivery is unavailable until the notification SET.',
  diagnosticsTitle: 'Diagnostics',
  diagnosticsDescription: 'Live, sanitized state reported by Jupiter Core.',
  version: 'Version',
  build: 'Build',
  commit: 'Commit',
  runtime: 'Runtime',
  database: 'Database',
  schemaJournal: 'Schema / journal',
  integrityForeignKeys: 'Integrity / foreign keys',
  records: 'Persistent records',
  enabled: 'Enabled',
  disabled: 'Disabled',
  events: 'events',
  auditEntries: 'audit entries',
  serviceHealth: 'Service health',
  noServiceData: 'No service health data is available.',
  loadFailed: 'Jupiter could not load its trusted runtime state.',
  failureNextStep: 'Open Diagnostics or retry when Core is available.',
  unknownRuntimeError: 'An unknown runtime error occurred.',
} as const;

export type CopyKey = keyof typeof en;
export type Translator = (key: CopyKey) => string;

const th: Record<CopyKey, string> = {
  appName: 'Jupiter',
  appShell: 'ศูนย์ควบคุม Jupiter',
  skipToContent: 'ข้ามไปยังเนื้อหาหลัก',
  primaryNavigation: 'เมนูหลัก',
  collapseNavigation: 'ย่อเมนู',
  expandNavigation: 'ขยายเมนู',
  home: 'หน้าหลัก',
  chat: 'แชต',
  missions: 'ภารกิจ',
  skills: 'ทักษะ',
  memory: 'ความจำ',
  files: 'ไฟล์',
  automations: 'ระบบอัตโนมัติ',
  models: 'โมเดล AI',
  devices: 'อุปกรณ์',
  plugins: 'ปลั๊กอิน',
  settings: 'การตั้งค่า',
  diagnostics: 'การวินิจฉัย',
  operational: 'ทำงานปกติ',
  degraded: 'ทำงานแบบจำกัด',
  offline: 'ออฟไลน์',
  unavailable: 'ยังไม่พร้อมใช้งาน',
  notConfigured: 'ยังไม่ได้กำหนดค่า',
  comingLater: 'พร้อมในภายหลัง',
  experimental: 'ทดลองใช้งาน',
  loading: 'กำลังตรวจสอบ Jupiter Core…',
  retry: 'ลองอีกครั้ง',
  close: 'ปิด',
  refresh: 'ตรวจสุขภาพอีกครั้ง',
  saveError: 'Jupiter ไม่สามารถบันทึกการตั้งค่านี้ได้',
  preferenceSaved: 'บันทึกการตั้งค่าแล้ว',
  toastRegion: 'การแจ้งเตือนจาก Jupiter',
  coreOnline: 'Jupiter Core ออนไลน์',
  coreLimited: 'Jupiter Core พร้อมใช้งานแบบจำกัด',
  coreUnavailable: 'Jupiter Core ไม่พร้อมใช้งาน',
  homeEyebrow: 'ศูนย์ควบคุม',
  homeTitle: 'พร้อมเมื่อกำหนดค่าความสามารถจริงแล้ว',
  homeDescription:
    'Jupiter Core เชื่อมต่อแล้ว แต่ Agent โมเดล และระบบภารกิจยังไม่พร้อมจนกว่าจะพัฒนาถึง SET ที่เกี่ยวข้อง',
  currentMission: 'ภารกิจปัจจุบัน',
  noActiveMission: 'ไม่มีภารกิจที่กำลังทำงาน',
  noActiveMissionDescription: 'ระบบภารกิจจะพร้อมใน SET ถัดไป ขณะนี้ Jupiter ไม่ได้ทำงานเบื้องหลัง',
  progressUnavailable: 'ไม่มีข้อมูลความคืบหน้า',
  elapsedTime: 'เวลาที่ใช้',
  agent: 'Agent',
  skill: 'ทักษะ',
  model: 'โมเดล',
  none: 'ไม่มี',
  pause: 'หยุดชั่วคราว',
  cancel: 'ยกเลิก',
  details: 'รายละเอียด',
  timeline: 'ลำดับกิจกรรม',
  timelineEmpty: 'ยังไม่มีกิจกรรมจาก Core ในเซสชัน UI นี้',
  eventCoreStarted: 'Jupiter Core เริ่มทำงาน',
  eventCoreStopped: 'Jupiter Core หยุดทำงาน',
  eventServiceHealth: 'สถานะบริการเปลี่ยนแปลง',
  eventPreferencesUpdated: 'อัปเดตการตั้งค่าหน้าจอแล้ว',
  eventRecorded: 'บันทึกเหตุการณ์จาก Core แล้ว',
  chatTitle: 'แชต',
  chatDescription: 'ยังไม่ได้กำหนดผู้ให้บริการ AI และระบบแชตใน SET 2',
  composerLabel: 'ช่องพิมพ์ข้อความ',
  composerPlaceholder: 'ยังไม่ได้กำหนดผู้ให้บริการ AI',
  send: 'ส่ง',
  missionsTitle: 'ภารกิจ',
  missionsDescription: 'การวางแผนและดำเนินภารกิจจะพร้อมใน SET ภายหลัง',
  skillsTitle: 'ทักษะ',
  skillsDescription: 'ยังไม่มีทักษะติดตั้ง เนื่องจากระบบทักษะยังไม่ได้พัฒนา',
  memoryTitle: 'ความจำ',
  memoryDescription: 'Jupiter ยังไม่บันทึกความจำส่วนบุคคลใน SET 2',
  filesTitle: 'ไฟล์และผลงาน',
  filesDescription: 'ยังไม่มีโฟลเดอร์ที่อนุมัติและยังไม่มีผลงานที่ระบบจัดการ',
  automationsTitle: 'ระบบอัตโนมัติ',
  automationsDescription: 'ไม่มีตารางเวลาหรือระบบอัตโนมัติทำงานอยู่',
  modelsTitle: 'โมเดล AI',
  modelsDescription: 'ยังไม่ได้กำหนดผู้ให้บริการ AI แบบคลาวด์หรือภายในเครื่อง',
  devicesTitle: 'อุปกรณ์',
  devicesDescription: 'ยังไม่ได้เชื่อมต่อไมโครโฟน กล้อง หรืออุปกรณ์เสริม',
  pluginsTitle: 'ปลั๊กอิน',
  pluginsDescription: 'ยังไม่ได้เปิดใช้งาน runtime ของปลั๊กอินภายนอก',
  settingsTitle: 'การตั้งค่า',
  settingsDescription: 'การตั้งค่าหน้าจอเหล่านี้ใช้งานจริงและบันทึกไว้ในเครื่อง',
  appearance: 'รูปลักษณ์',
  accessibility: 'การช่วยการเข้าถึง',
  safetyInterfaces: 'ส่วนติดต่อด้านความปลอดภัย',
  language: 'ภาษา',
  english: 'English',
  thai: 'ไทย',
  theme: 'ธีม',
  darkTheme: 'กราไฟต์',
  midnightTheme: 'มิดไนต์',
  avatar: 'อวตาร Jupiter',
  avatarAnimated: 'เคลื่อนไหว',
  avatarStatic: 'ภาพนิ่ง',
  avatarHidden: 'ซ่อน',
  reduceMotion: 'ลดการเคลื่อนไหว',
  compactMode: 'โหมดกะทัดรัด',
  textScale: 'ขนาดตัวอักษร',
  permissionInterface: 'หน้าต่างขออนุญาต',
  identityInterface: 'หน้าต่างยืนยันตัวตน',
  viewAvailability: 'ดูรายละเอียดความพร้อม',
  permissionTitle: 'การยืนยันสิทธิ์',
  permissionDescription: 'ระบบสิทธิ์ยังไม่พร้อมใช้งาน',
  permissionBody:
    'หน้าต่างนี้รองรับการช่วยการเข้าถึง แต่ยังอนุมัติการกระทำไม่ได้จนกว่าจะพัฒนาระบบสิทธิ์',
  identityTitle: 'การยืนยันตัวตน',
  identityDescription: 'ระบบตัวตนยังไม่พร้อมใช้งาน',
  identityBody: 'ระบบจะไม่เก็บหรือจำลองหลักฐานตัวตน การยืนยันตัวตนจะพร้อมใน SET ภายหลัง',
  windowsNotifications: 'การแจ้งเตือนของ Windows',
  windowsNotificationsBody:
    'มี interface สำหรับเชื่อมต่อแล้ว แต่การส่งจริงจะพร้อมใน SET การแจ้งเตือน',
  diagnosticsTitle: 'การวินิจฉัย',
  diagnosticsDescription: 'สถานะจริงที่ผ่านการกรองข้อมูลสำคัญจาก Jupiter Core',
  version: 'เวอร์ชัน',
  build: 'บิลด์',
  commit: 'คอมมิต',
  runtime: 'ระบบทำงาน',
  database: 'ฐานข้อมูล',
  schemaJournal: 'สคีมา / เจอร์นัล',
  integrityForeignKeys: 'ความสมบูรณ์ / foreign keys',
  records: 'ระเบียนถาวร',
  enabled: 'เปิด',
  disabled: 'ปิด',
  events: 'เหตุการณ์',
  auditEntries: 'รายการตรวจสอบ',
  serviceHealth: 'สุขภาพบริการ',
  noServiceData: 'ไม่มีข้อมูลสุขภาพบริการ',
  loadFailed: 'Jupiter ไม่สามารถโหลดสถานะระบบที่เชื่อถือได้',
  failureNextStep: 'เปิดหน้าวินิจฉัยหรือลองใหม่เมื่อ Core พร้อมใช้งาน',
  unknownRuntimeError: 'เกิดข้อผิดพลาดที่ไม่ทราบสาเหตุในระบบ',
};

const COPY: Record<Language, Record<CopyKey, string>> = { en, th };

export function createTranslator(language: Language): Translator {
  return (key) => COPY[language][key];
}

export function preferredLanguage(): Language {
  return navigator.language.toLowerCase().startsWith('th') ? 'th' : 'en';
}
