import type { Language } from '@jupiter/contracts';

const en = {
  appName: 'Jupiter',
  appShell: 'Jupiter command center',
  skipToContent: 'Skip to main content',
  primaryNavigation: 'Primary navigation',
  collapseNavigation: 'Collapse navigation',
  expandNavigation: 'Expand navigation',
  home: 'Home',
  chat: 'Chat',
  missions: 'Missions',
  skills: 'Skills',
  memory: 'Memory',
  files: 'Files',
  automations: 'Automations',
  models: 'AI Models',
  devices: 'Devices',
  plugins: 'Plugins',
  settings: 'Settings',
  diagnostics: 'Diagnostics',
  operational: 'Operational',
  degraded: 'Degraded',
  offline: 'Offline',
  unavailable: 'Unavailable',
  notConfigured: 'Not configured',
  comingLater: 'Coming later',
  experimental: 'Experimental',
  loading: 'Checking Jupiter Core…',
  retry: 'Retry',
  close: 'Close',
  refresh: 'Refresh health',
  saveError: 'Jupiter could not save that preference.',
  preferenceSaved: 'Preference saved',
  toastRegion: 'Jupiter notifications',
  coreOnline: 'Jupiter Core online',
  coreLimited: 'Jupiter Core has limited availability',
  coreUnavailable: 'Jupiter Core unavailable',
  homeEyebrow: 'Command Center',
  homeTitle: 'Ready when real capabilities are configured.',
  homeDescription:
    'Jupiter Core is connected. Chat and durable Mission records are available; planning and execution remain explicitly unavailable.',
  currentMission: 'Current Mission',
  noActiveMission: 'No active Mission',
  noActiveMissionDescription:
    'Create a durable request in Missions. Jupiter is not running background work without a real execution plan.',
  progressUnavailable: 'Progress unavailable',
  elapsedTime: 'Elapsed time',
  agent: 'Agent',
  skill: 'Skill',
  model: 'Model',
  none: 'None',
  pause: 'Pause',
  cancel: 'Cancel',
  details: 'Details',
  timeline: 'Activity timeline',
  timelineEmpty: 'No Core activity has been recorded in this UI session.',
  eventCoreStarted: 'Jupiter Core started',
  eventCoreStopped: 'Jupiter Core stopped',
  eventServiceHealth: 'Service health changed',
  eventPreferencesUpdated: 'Interface preferences updated',
  eventRecorded: 'Core event recorded',
  chatTitle: 'Chat',
  chatDescription: 'Durable conversations with explicit provider routing and cancelable streaming.',
  composerLabel: 'Message composer',
  composerPlaceholder: 'AI provider not configured',
  composerReadyPlaceholder: 'Ask Jupiter…',
  send: 'Send',
  openChat: 'Open Chat',
  newConversation: 'New conversation',
  conversationHistory: 'Conversation history',
  providerAuto: 'Automatic routing',
  useGlobalSetting: 'Use global setting',
  provider: 'Provider',
  assistant: 'Jupiter',
  you: 'You',
  tool: 'Tool',
  chatReadyDescription:
    'Send a message to the configured provider. Responses are persisted locally.',
  configureProviderFirst: 'Configure and validate a provider before sending a message.',
  noMessages: 'No messages yet',
  waitingForProvider: 'Waiting for provider…',
  configureProviders: 'Configure providers',
  attachmentsUnavailable: 'Attachments unavailable',
  editAndResend: 'Edit and resend',
  cancelEdit: 'Cancel edit',
  stopGeneration: 'Stop generation',
  emptyProviderResponse: 'Provider returned an empty response.',
  toolCall: 'Tool call',
  edit: 'Edit',
  missionsTitle: 'Missions',
  missionsDescription: 'Mission planning and execution arrive in a later SET.',
  skillsTitle: 'Skills',
  skillsDescription: 'No Skills are installed because the Skill system is not implemented yet.',
  memoryTitle: 'Memory',
  memoryDescription: 'Jupiter is not saving personal memory in SET 2.',
  filesTitle: 'Files and artifacts',
  filesDescription: 'No file roots are approved and no artifacts are managed yet.',
  automationsTitle: 'Automations',
  automationsDescription: 'No schedules or background automations are running.',
  modelsTitle: 'AI Models',
  modelsDescription:
    'Configure installed OpenAI-compatible cloud or local endpoints and routing policy.',
  addProvider: 'Add or update provider',
  providerFormDescription:
    'Only configured endpoints appear in Jupiter. Cloud endpoints require HTTPS; local endpoints require loopback.',
  providerId: 'Provider ID',
  displayName: 'Display name',
  endpoint: 'Base endpoint',
  providerLocation: 'Location',
  localProvider: 'Local endpoint',
  cloudProvider: 'Cloud endpoint',
  authentication: 'Authentication',
  noCredential: 'No credential',
  bearerCredential: 'Bearer credential',
  apiCredential: 'API credential',
  providerCapabilities: 'Supported capabilities',
  capabilityChat: 'Chat',
  capabilityStreaming: 'Streaming',
  capabilityReasoning: 'Reasoning',
  capabilityVision: 'Vision',
  capabilityEmbeddings: 'Embeddings',
  capabilityToolCalling: 'Tool calling',
  capabilityStructuredOutput: 'Structured output',
  capabilityCancellation: 'Cancellation',
  capabilityUsage: 'Usage reporting',
  credentialSecurityNote:
    'Credentials are encrypted with Windows DPAPI and are never returned to this screen.',
  validating: 'Validating…',
  saveAndValidate: 'Save and validate',
  providerSavedValidated: 'Provider saved and validated.',
  providerValidated: 'Provider validated.',
  providerRemoved: 'Provider configuration and encrypted credential removed.',
  routingSettings: 'Model routing',
  routingMode: 'Routing mode',
  preferredProvider: 'Preferred provider',
  preferredChatModel: 'Preferred chat model',
  preferredReasoningModel: 'Preferred reasoning model',
  preferredVisionModel: 'Preferred vision model',
  preferredEmbeddingModel: 'Preferred embedding model',
  fallbackPolicy: 'Fallback policy',
  noFallback: 'No fallback',
  sameLocalityFallback: 'Same locality only',
  explicitFallback: 'Explicit provider list',
  approvedFallbackProviders: 'Approved fallback providers',
  optimization: 'Optimization',
  balanced: 'Balanced',
  cost: 'Cost',
  latency: 'Latency',
  localOnlyDescription:
    'LOCAL_ONLY blocks every cloud provider at the routing boundary. Fallback never overrides this rule.',
  routingSaved: 'Routing settings saved.',
  configuredProviders: 'Configured providers',
  noProviders: 'No providers configured',
  noProvidersDescription:
    'Add a compatible endpoint above. Jupiter will not assume commercial availability.',
  credentialFingerprint: 'Credential fingerprint',
  discoveredModels: 'Discovered models',
  validateAgain: 'Validate again',
  confirmProviderRemoval: 'Remove this exact provider and its encrypted credential?',
  confirmRemove: 'Confirm remove',
  remove: 'Remove',
  devicesTitle: 'Devices',
  devicesDescription: 'Microphone, camera, and companion devices are not connected.',
  pluginsTitle: 'Plugins',
  pluginsDescription: 'No third-party plugin runtime is enabled.',
  settingsTitle: 'Settings',
  settingsDescription: 'These interface preferences are real and persist locally.',
  appearance: 'Appearance',
  accessibility: 'Accessibility',
  safetyInterfaces: 'Safety interfaces',
  language: 'Language',
  english: 'English',
  thai: 'ไทย',
  theme: 'Theme',
  darkTheme: 'Graphite',
  midnightTheme: 'Midnight',
  avatar: 'Jupiter avatar',
  avatarAnimated: 'Animated',
  avatarStatic: 'Static',
  avatarHidden: 'Hidden',
  reduceMotion: 'Reduce motion',
  compactMode: 'Compact mode',
  textScale: 'Text size',
  permissionInterface: 'Permission dialog',
  identityInterface: 'Identity dialog',
  viewAvailability: 'View availability details',
  permissionTitle: 'Permission confirmation',
  permissionDescription: 'Permission Engine unavailable',
  permissionBody:
    'This dialog shell is accessible, but it cannot approve actions until the Permission Engine is implemented.',
  identityTitle: 'Identity verification',
  identityDescription: 'Identity Engine unavailable',
  identityBody:
    'No identity proof is collected or simulated. Identity verification arrives in a later SET.',
  windowsNotifications: 'Windows notifications',
  windowsNotificationsBody:
    'Bridge interface available; native delivery is unavailable until the notification SET.',
  diagnosticsTitle: 'Diagnostics',
  diagnosticsDescription: 'Live, sanitized state reported by Jupiter Core.',
  version: 'Version',
  build: 'Build',
  commit: 'Commit',
  runtime: 'Runtime',
  database: 'Database',
  schemaJournal: 'Schema / journal',
  integrityForeignKeys: 'Integrity / foreign keys',
  records: 'Persistent records',
  enabled: 'Enabled',
  disabled: 'Disabled',
  events: 'events',
  auditEntries: 'audit entries',
  serviceHealth: 'Service health',
  noServiceData: 'No service health data is available.',
  loadFailed: 'Jupiter could not load its trusted runtime state.',
  failureNextStep: 'Open Diagnostics or retry when Core is available.',
  unknownRuntimeError: 'An unknown runtime error occurred.',
} as const;

export type CopyKey = keyof typeof en;
export type Translator = (key: CopyKey) => string;

const th: Record<CopyKey, string> = {
  appName: 'Jupiter',
  appShell: 'ศูนย์ควบคุม Jupiter',
  skipToContent: 'ข้ามไปยังเนื้อหาหลัก',
  primaryNavigation: 'เมนูหลัก',
  collapseNavigation: 'ย่อเมนู',
  expandNavigation: 'ขยายเมนู',
  home: 'หน้าหลัก',
  chat: 'แชต',
  missions: 'ภารกิจ',
  skills: 'ทักษะ',
  memory: 'ความจำ',
  files: 'ไฟล์',
  automations: 'ระบบอัตโนมัติ',
  models: 'โมเดล AI',
  devices: 'อุปกรณ์',
  plugins: 'ปลั๊กอิน',
  settings: 'การตั้งค่า',
  diagnostics: 'การวินิจฉัย',
  operational: 'ทำงานปกติ',
  degraded: 'ทำงานแบบจำกัด',
  offline: 'ออฟไลน์',
  unavailable: 'ยังไม่พร้อมใช้งาน',
  notConfigured: 'ยังไม่ได้กำหนดค่า',
  comingLater: 'พร้อมในภายหลัง',
  experimental: 'ทดลองใช้งาน',
  loading: 'กำลังตรวจสอบ Jupiter Core…',
  retry: 'ลองอีกครั้ง',
  close: 'ปิด',
  refresh: 'ตรวจสุขภาพอีกครั้ง',
  saveError: 'Jupiter ไม่สามารถบันทึกการตั้งค่านี้ได้',
  preferenceSaved: 'บันทึกการตั้งค่าแล้ว',
  toastRegion: 'การแจ้งเตือนจาก Jupiter',
  coreOnline: 'Jupiter Core ออนไลน์',
  coreLimited: 'Jupiter Core พร้อมใช้งานแบบจำกัด',
  coreUnavailable: 'Jupiter Core ไม่พร้อมใช้งาน',
  homeEyebrow: 'ศูนย์ควบคุม',
  homeTitle: 'พร้อมเมื่อกำหนดค่าความสามารถจริงแล้ว',
  homeDescription:
    'Jupiter Core เชื่อมต่อแล้ว แชตและข้อมูลภารกิจแบบถาวรพร้อมใช้งาน ส่วนการวางแผนและดำเนินงานยังไม่พร้อม',
  currentMission: 'ภารกิจปัจจุบัน',
  noActiveMission: 'ไม่มีภารกิจที่กำลังทำงาน',
  noActiveMissionDescription:
    'สร้างคำขอแบบถาวรได้ในหน้าภารกิจ Jupiter จะไม่ทำงานเบื้องหลังหากยังไม่มีแผนดำเนินงานจริง',
  progressUnavailable: 'ไม่มีข้อมูลความคืบหน้า',
  elapsedTime: 'เวลาที่ใช้',
  agent: 'Agent',
  skill: 'ทักษะ',
  model: 'โมเดล',
  none: 'ไม่มี',
  pause: 'หยุดชั่วคราว',
  cancel: 'ยกเลิก',
  details: 'รายละเอียด',
  timeline: 'ลำดับกิจกรรม',
  timelineEmpty: 'ยังไม่มีกิจกรรมจาก Core ในเซสชัน UI นี้',
  eventCoreStarted: 'Jupiter Core เริ่มทำงาน',
  eventCoreStopped: 'Jupiter Core หยุดทำงาน',
  eventServiceHealth: 'สถานะบริการเปลี่ยนแปลง',
  eventPreferencesUpdated: 'อัปเดตการตั้งค่าหน้าจอแล้ว',
  eventRecorded: 'บันทึกเหตุการณ์จาก Core แล้ว',
  chatTitle: 'แชต',
  chatDescription: 'การสนทนาแบบถาวร พร้อมการเลือกผู้ให้บริการอย่างชัดเจนและการสตรีมที่ยกเลิกได้',
  composerLabel: 'ช่องพิมพ์ข้อความ',
  composerPlaceholder: 'ยังไม่ได้กำหนดผู้ให้บริการ AI',
  composerReadyPlaceholder: 'ถาม Jupiter…',
  send: 'ส่ง',
  openChat: 'เปิดแชต',
  newConversation: 'การสนทนาใหม่',
  conversationHistory: 'ประวัติการสนทนา',
  providerAuto: 'เลือกเส้นทางอัตโนมัติ',
  useGlobalSetting: 'ใช้การตั้งค่าส่วนกลาง',
  provider: 'ผู้ให้บริการ',
  assistant: 'Jupiter',
  you: 'คุณ',
  tool: 'เครื่องมือ',
  chatReadyDescription: 'ส่งข้อความไปยังผู้ให้บริการที่กำหนดค่าไว้ คำตอบจะบันทึกในเครื่อง',
  configureProviderFirst: 'กำหนดค่าและตรวจสอบผู้ให้บริการก่อนส่งข้อความ',
  noMessages: 'ยังไม่มีข้อความ',
  waitingForProvider: 'กำลังรอผู้ให้บริการ…',
  configureProviders: 'กำหนดค่าผู้ให้บริการ',
  attachmentsUnavailable: 'ไฟล์แนบยังไม่พร้อมใช้งาน',
  editAndResend: 'แก้ไขและส่งอีกครั้ง',
  cancelEdit: 'ยกเลิกการแก้ไข',
  stopGeneration: 'หยุดการสร้างคำตอบ',
  emptyProviderResponse: 'ผู้ให้บริการส่งคำตอบว่างกลับมา',
  toolCall: 'การเรียกเครื่องมือ',
  edit: 'แก้ไข',
  missionsTitle: 'ภารกิจ',
  missionsDescription: 'การวางแผนและดำเนินภารกิจจะพร้อมใน SET ภายหลัง',
  skillsTitle: 'ทักษะ',
  skillsDescription: 'ยังไม่มีทักษะติดตั้ง เนื่องจากระบบทักษะยังไม่ได้พัฒนา',
  memoryTitle: 'ความจำ',
  memoryDescription: 'Jupiter ยังไม่บันทึกความจำส่วนบุคคลใน SET 2',
  filesTitle: 'ไฟล์และผลงาน',
  filesDescription: 'ยังไม่มีโฟลเดอร์ที่อนุมัติและยังไม่มีผลงานที่ระบบจัดการ',
  automationsTitle: 'ระบบอัตโนมัติ',
  automationsDescription: 'ไม่มีตารางเวลาหรือระบบอัตโนมัติทำงานอยู่',
  modelsTitle: 'โมเดล AI',
  modelsDescription:
    'กำหนดค่า endpoint แบบ OpenAI-compatible ทั้งคลาวด์และภายในเครื่อง พร้อมนโยบายเลือกโมเดล',
  addProvider: 'เพิ่มหรือแก้ไขผู้ให้บริการ',
  providerFormDescription:
    'Jupiter จะแสดงเฉพาะ endpoint ที่กำหนดค่าแล้ว คลาวด์ต้องใช้ HTTPS และภายในเครื่องต้องใช้ loopback',
  providerId: 'รหัสผู้ให้บริการ',
  displayName: 'ชื่อที่แสดง',
  endpoint: 'Base endpoint',
  providerLocation: 'ตำแหน่ง',
  localProvider: 'Endpoint ภายในเครื่อง',
  cloudProvider: 'Endpoint คลาวด์',
  authentication: 'การยืนยันตัวตน',
  noCredential: 'ไม่ใช้ข้อมูลลับ',
  bearerCredential: 'Bearer credential',
  apiCredential: 'ข้อมูลลับ API',
  providerCapabilities: 'ความสามารถที่รองรับ',
  capabilityChat: 'แชต',
  capabilityStreaming: 'สตรีมมิง',
  capabilityReasoning: 'การให้เหตุผล',
  capabilityVision: 'การประมวลผลภาพ',
  capabilityEmbeddings: 'Embedding',
  capabilityToolCalling: 'การเรียกใช้เครื่องมือ',
  capabilityStructuredOutput: 'ผลลัพธ์แบบมีโครงสร้าง',
  capabilityCancellation: 'การยกเลิก',
  capabilityUsage: 'รายงานการใช้งาน',
  credentialSecurityNote: 'ข้อมูลลับเข้ารหัสด้วย Windows DPAPI และจะไม่ถูกส่งกลับมาแสดงในหน้าจอนี้',
  validating: 'กำลังตรวจสอบ…',
  saveAndValidate: 'บันทึกและตรวจสอบ',
  providerSavedValidated: 'บันทึกและตรวจสอบผู้ให้บริการแล้ว',
  providerValidated: 'ตรวจสอบผู้ให้บริการแล้ว',
  providerRemoved: 'ลบการตั้งค่าและข้อมูลลับที่เข้ารหัสของผู้ให้บริการแล้ว',
  routingSettings: 'การเลือกเส้นทางโมเดล',
  routingMode: 'โหมดการเลือกเส้นทาง',
  preferredProvider: 'ผู้ให้บริการที่ต้องการ',
  preferredChatModel: 'โมเดลแชตที่ต้องการ',
  preferredReasoningModel: 'โมเดลการให้เหตุผลที่ต้องการ',
  preferredVisionModel: 'โมเดลภาพที่ต้องการ',
  preferredEmbeddingModel: 'โมเดล Embedding ที่ต้องการ',
  fallbackPolicy: 'นโยบายสำรอง',
  noFallback: 'ไม่ใช้ตัวสำรอง',
  sameLocalityFallback: 'เฉพาะตำแหน่งเดียวกัน',
  explicitFallback: 'รายชื่อผู้ให้บริการที่อนุญาต',
  approvedFallbackProviders: 'ผู้ให้บริการสำรองที่อนุมัติ',
  optimization: 'การปรับให้เหมาะสม',
  balanced: 'สมดุล',
  cost: 'ค่าใช้จ่าย',
  latency: 'ความหน่วง',
  localOnlyDescription:
    'LOCAL_ONLY บล็อกผู้ให้บริการคลาวด์ทั้งหมดที่จุดเลือกเส้นทาง และตัวสำรองไม่สามารถข้ามกฎนี้ได้',
  routingSaved: 'บันทึกการตั้งค่าเส้นทางแล้ว',
  configuredProviders: 'ผู้ให้บริการที่กำหนดค่าแล้ว',
  noProviders: 'ยังไม่มีผู้ให้บริการ',
  noProvidersDescription:
    'เพิ่ม endpoint ที่เข้ากันได้ด้านบน Jupiter จะไม่สมมติว่าค่ายใดพร้อมใช้งาน',
  credentialFingerprint: 'ลายนิ้วมือข้อมูลลับ',
  discoveredModels: 'โมเดลที่ค้นพบ',
  validateAgain: 'ตรวจสอบอีกครั้ง',
  confirmProviderRemoval: 'ลบผู้ให้บริการนี้และข้อมูลลับที่เข้ารหัสใช่หรือไม่',
  confirmRemove: 'ยืนยันการลบ',
  remove: 'ลบ',
  devicesTitle: 'อุปกรณ์',
  devicesDescription: 'ยังไม่ได้เชื่อมต่อไมโครโฟน กล้อง หรืออุปกรณ์เสริม',
  pluginsTitle: 'ปลั๊กอิน',
  pluginsDescription: 'ยังไม่ได้เปิดใช้งาน runtime ของปลั๊กอินภายนอก',
  settingsTitle: 'การตั้งค่า',
  settingsDescription: 'การตั้งค่าหน้าจอเหล่านี้ใช้งานจริงและบันทึกไว้ในเครื่อง',
  appearance: 'รูปลักษณ์',
  accessibility: 'การช่วยการเข้าถึง',
  safetyInterfaces: 'ส่วนติดต่อด้านความปลอดภัย',
  language: 'ภาษา',
  english: 'English',
  thai: 'ไทย',
  theme: 'ธีม',
  darkTheme: 'กราไฟต์',
  midnightTheme: 'มิดไนต์',
  avatar: 'อวตาร Jupiter',
  avatarAnimated: 'เคลื่อนไหว',
  avatarStatic: 'ภาพนิ่ง',
  avatarHidden: 'ซ่อน',
  reduceMotion: 'ลดการเคลื่อนไหว',
  compactMode: 'โหมดกะทัดรัด',
  textScale: 'ขนาดตัวอักษร',
  permissionInterface: 'หน้าต่างขออนุญาต',
  identityInterface: 'หน้าต่างยืนยันตัวตน',
  viewAvailability: 'ดูรายละเอียดความพร้อม',
  permissionTitle: 'การยืนยันสิทธิ์',
  permissionDescription: 'ระบบสิทธิ์ยังไม่พร้อมใช้งาน',
  permissionBody:
    'หน้าต่างนี้รองรับการช่วยการเข้าถึง แต่ยังอนุมัติการกระทำไม่ได้จนกว่าจะพัฒนาระบบสิทธิ์',
  identityTitle: 'การยืนยันตัวตน',
  identityDescription: 'ระบบตัวตนยังไม่พร้อมใช้งาน',
  identityBody: 'ระบบจะไม่เก็บหรือจำลองหลักฐานตัวตน การยืนยันตัวตนจะพร้อมใน SET ภายหลัง',
  windowsNotifications: 'การแจ้งเตือนของ Windows',
  windowsNotificationsBody:
    'มี interface สำหรับเชื่อมต่อแล้ว แต่การส่งจริงจะพร้อมใน SET การแจ้งเตือน',
  diagnosticsTitle: 'การวินิจฉัย',
  diagnosticsDescription: 'สถานะจริงที่ผ่านการกรองข้อมูลสำคัญจาก Jupiter Core',
  version: 'เวอร์ชัน',
  build: 'บิลด์',
  commit: 'คอมมิต',
  runtime: 'ระบบทำงาน',
  database: 'ฐานข้อมูล',
  schemaJournal: 'สคีมา / เจอร์นัล',
  integrityForeignKeys: 'ความสมบูรณ์ / foreign keys',
  records: 'ระเบียนถาวร',
  enabled: 'เปิด',
  disabled: 'ปิด',
  events: 'เหตุการณ์',
  auditEntries: 'รายการตรวจสอบ',
  serviceHealth: 'สุขภาพบริการ',
  noServiceData: 'ไม่มีข้อมูลสุขภาพบริการ',
  loadFailed: 'Jupiter ไม่สามารถโหลดสถานะระบบที่เชื่อถือได้',
  failureNextStep: 'เปิดหน้าวินิจฉัยหรือลองใหม่เมื่อ Core พร้อมใช้งาน',
  unknownRuntimeError: 'เกิดข้อผิดพลาดที่ไม่ทราบสาเหตุในระบบ',
};

const COPY: Record<Language, Record<CopyKey, string>> = { en, th };

export function createTranslator(language: Language): Translator {
  return (key) => COPY[language][key];
}

export function preferredLanguage(): Language {
  return navigator.language.toLowerCase().startsWith('th') ? 'th' : 'en';
}
