import type { Language } from '@jupiter/contracts';

const copy = {
  en: {
    title: 'Permission Center',
    description: 'Capability decisions from Jupiter Core',
    refresh: 'Refresh',
    pending: 'Pending requests',
    noPending: 'No action is waiting for permission.',
    action: 'Action',
    reason: 'Why this is needed',
    target: 'Exact target',
    scope: 'Approved scope',
    risk: 'Risk',
    requester: 'Requester',
    mission: 'Mission / step',
    data: 'Data leaving this device',
    consequence: 'Consequence',
    reversible: 'Reversible',
    automation: 'Automated action',
    yes: 'Yes',
    no: 'No',
    approveOnce: 'Allow once',
    approveSession: 'Allow this session',
    alwaysAllow: 'Always allow',
    deny: 'Deny',
    grants: 'Persisted and session decisions',
    noGrants: 'No permission decisions are stored.',
    revoke: 'Revoke',
    revoked: 'Revoked',
    consumed: 'Consumed',
    active: 'Active',
    audit: 'Sanitized decision audit',
    noAudit: 'No permission decision has been recorded.',
    capabilities: 'Declared capabilities',
    criticalNotice:
      'Critical actions require confirmation every time. Always allow is unavailable.',
    loadError: 'Permission data could not be loaded.',
  },
  th: {
    title: 'ศูนย์จัดการสิทธิ์',
    description: 'การตัดสินสิทธิ์ตามความสามารถจาก Jupiter Core',
    refresh: 'รีเฟรช',
    pending: 'คำขอที่รอการตัดสิน',
    noPending: 'ไม่มีการกระทำที่กำลังรอสิทธิ์',
    action: 'สิ่งที่ Jupiter ต้องการทำ',
    reason: 'เหตุผลที่จำเป็น',
    target: 'เป้าหมายที่แน่นอน',
    scope: 'ขอบเขตที่อนุญาต',
    risk: 'ระดับความเสี่ยง',
    requester: 'ผู้ร้องขอ',
    mission: 'ภารกิจ / ขั้นตอน',
    data: 'ข้อมูลที่ออกจากเครื่อง',
    consequence: 'ผลที่อาจเกิดขึ้น',
    reversible: 'ย้อนกลับได้',
    automation: 'การกระทำอัตโนมัติ',
    yes: 'ใช่',
    no: 'ไม่',
    approveOnce: 'อนุญาตครั้งเดียว',
    approveSession: 'อนุญาตในเซสชันนี้',
    alwaysAllow: 'อนุญาตเสมอ',
    deny: 'ปฏิเสธ',
    grants: 'การตัดสินที่บันทึกไว้และในเซสชัน',
    noGrants: 'ยังไม่มีการตัดสินสิทธิ์ที่จัดเก็บไว้',
    revoke: 'เพิกถอน',
    revoked: 'เพิกถอนแล้ว',
    consumed: 'ใช้ไปแล้ว',
    active: 'ใช้งานอยู่',
    audit: 'ประวัติการตัดสินแบบปกปิดข้อมูลสำคัญ',
    noAudit: 'ยังไม่มีประวัติการตัดสินสิทธิ์',
    capabilities: 'ความสามารถที่ประกาศไว้',
    criticalNotice: 'การกระทำระดับวิกฤตต้องยืนยันทุกครั้ง และไม่มีตัวเลือกอนุญาตเสมอ',
    loadError: 'ไม่สามารถโหลดข้อมูลสิทธิ์ได้',
  },
} as const;

export function permissionCopy(language: Language) {
  return copy[language];
}
